name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    continue-on-error: ${{ matrix.config.continue-on-error == 'true' }}
    strategy:
      matrix:
        config:
          - {dockerfile: 'fedora',   tag: 'latest'}
          - {dockerfile: 'fedora',   tag: 'rawhide',   build_args: 'TAG=rawhide', continue-on-error: 'true'}
          - {dockerfile: 'ubuntu',   tag: 'latest'}
          - {dockerfile: 'ubuntu',   tag: 'rolling',   build_args: 'TAG=rolling'}
          - {dockerfile: 'ubuntu',   tag: 'devel',     build_args: 'TAG=devel', continue-on-error: 'true'}
          - {dockerfile: 'ubuntu',   tag: '18.04',     build_args: 'TAG=18.04'}
          - {dockerfile: 'opensuse', tag: 'latest'}
          - {dockerfile: 'fedora',   tag: 'gmx2019_d', build_args: 'GMX_BRANCH=release-2019', build_args2: 'GMX_DOUBLE=ON'}
          - {dockerfile: 'fedora',   tag: 'gmx2019',   build_args: 'GMX_BRANCH=release-2019'}
          - {dockerfile: 'fedora',   tag: 'gmx2020_d', build_args: 'GMX_BRANCH=release-2020', build_args2: 'GMX_DOUBLE=ON'}
          - {dockerfile: 'fedora',   tag: 'gmx2020',   build_args: 'GMX_BRANCH=release-2020'}
          - {dockerfile: 'fedora',   tag: 'gmx2021_d', build_args: 'GMX_BRANCH=release-2021', build_args2: 'GMX_DOUBLE=ON'}
          - {dockerfile: 'fedora',   tag: 'gmx2021',   build_args: 'GMX_BRANCH=release-2021'}
          - {dockerfile: 'fedora',   tag: 'gmx9999_d', build_args: 'GMX_BRANCH=master', build_args2: 'GMX_DOUBLE=ON'}
          - {dockerfile: 'fedora',   tag: 'gmx9999',   build_args: 'GMX_BRANCH=master'}
          - {dockerfile: 'fedora',   tag: 'nogmx',     build_args: 'GMX_BRANCH=none'}
          - {dockerfile: 'fedora',   tag: 'intel',     build_args: 'INTEL=yes'}
          - {dockerfile: 'actions',  tag: 'latest'}
          - {dockerfile: 'format',   tag: 'latest'}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          buildkitd-flags: --debug
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/buildenv/${{ matrix.config.dockerfile }}:${{ matrix.config.tag }}
          file: ${{ matrix.config.dockerfile }}
          build-args: |
            ${{ matrix.config.build_args }}
            ${{ matrix.config.build_args2 }}
          pull: true
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
